[profile.default]
src = "src"
out = "out"
script = "script"
libs = ["lib"]
solc = '0.8.18'
ffi = true
auto_detect_solc = false

remappings = [
    'forge-std/=lib/forge-std/src',
    'cove-contracts-boosties/=lib/cove-contracts-boosties',
    'forge-safe/=lib/forge-safe/src',
    '@openzeppelin/=lib/cove-contracts-boosties/lib/openzeppelin-contracts/',
    'script/=script',
    'tokenized-strategy/=lib/cove-contracts-boosties/lib/tokenized-strategy/src',
    'permit2/=lib/cove-contracts-boosties/lib/permit2/src',
]

fs_permissions = [
    { access = "read", path = "./lib" },
    { access = "read", path = "./out" },
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
